version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install flask

  pre_build:
    commands:
      - echo Preparing build...

  build:
    commands:
      - echo Build started...
      - python app.py

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
